[com.blizzard.WoW] Use the com.blizzard.BattleNet.BaseApp Base App

diff --git a/com.blizzard.WoW/com.blizzard.WoW.yml b/com.blizzard.WoW/com.blizzard.WoW.yml
--- a/com.blizzard.WoW/com.blizzard.WoW.yml
+++ b/com.blizzard.WoW/com.blizzard.WoW.yml
@@ -5,15 +5,17 @@ runtime: org.winepak.Platform
 runtime-version: 3.0
 sdk: org.winepak.Sdk
 
+base: com.blizzard.BattleNet.BaseApp
+base-version: stable
+
 command: wow
 
+inherit-extensions:
+  - org.winepak.Platform.Compat32
+  - org.winepak.Platform.Extension.corefonts
+  - org.winepak.Platform.Extension.vcrun2015
+
 add-extensions:
-  org.winepak.Platform.Compat32:
-    directory: lib/32bit
-    version: 3.0
-    add-ld-path: lib
-    no-autodownload: false
-    
   org.winepak.Platform.Wine:
     directory: lib/wine
     version: 3.9-staging
@@ -26,11 +28,6 @@ add-extensions:
     add-ld-path: lib
     no-autodownload: false
     
-  org.winepak.Platform.Extension.corefonts:
-    directory: lib/extension/corefonts
-    version: 3.0
-    no-autodownload: false
-    
 tags:
   - proprietary
 
@@ -41,21 +38,9 @@ finish-args:
   - --share=network
   - --device=dri
   - --allow=multiarch
-  # --allow=devel is required to launch WoW
-  #
-  # Without it the game will partily launch then crash.
-  # 
-  # Ideally flatpak applications shouldn't have --allow=devel, so this needs to 
-  # be investigated.
   - --allow=devel
     
 modules:
-  - name: setup-compat32
-    buildsystem: simple
-    build-commands:
-      - mkdir -p /app/lib/32bit
-      - ln -s /app/lib/32bit/lib/ld-linux.so.2 /app/lib/ld-linux.so.2
-    
   - name: setup-wine
     buildsystem: simple
     build-commands:
@@ -65,11 +50,6 @@ modules:
     buildsystem: simple
     build-commands:
       - mkdir -p /app/lib/wine-32bit
-    
-  - name: setup
-    buildsystem: simple
-    build-commands:
-      - mkdir -p /app/lib/extension/corefonts
     
   - name: wow
     only-arches:
@@ -90,26 +70,20 @@ modules:
           - '    exit 1'
           - fi
           - 
-          - if [ -e "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Battle.net" ] ; then
+          - source /app/bin/battlenet-installer "battlenet://WoW"
+          -
+          - if [[ $? != 0 ]] ; then
+          - '    echo "Battle.net installer failed, abort."'
+          - '    exit 1'
+          - fi
+          - 
+          - if [ -e "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/World of Warcraft" ] ; then
           - '    echo "This prefix already has an exisiting ''World of Warcraft'' install at ${WINEPREFIX}"'
           - '    echo "In order to install ''World of Warcraft'' you must move or delete the current prefix."'
           - '    exit 1'
           - fi
           - 
-          - echo "Downloading installer..."
-          - curl -L --progress-bar --output "${XDG_CACHE_HOME}/wow-installer.exe" "https://www.battle.net/download/getInstallerForGame?os=win&version=LIVE&gameProgram=WOW"
-          - 
-          - echo "Setting-up wine prefix..."
-          - wineboot
-          - 
-          - echo "Installing Extension(s)..."
-          - echo "Installing vcrun2015..."
-          - source /app/lib/extension/corefonts/bin/corefonts-install64
-          - 
           - echo "Performing tweak(s)..."
-          - echo "Disable winemenubuilder.exe..."
-          - wine64 reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v winemenubuilder.exe /d '' /f
-          - 
           - echo "Clear Windows Version"
           - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v SubVersionNumber /f
           - wine64 reg delete 'HKLM\Software\Microsoft\Windows\CurrentVersion' /v VersionNumber /f
@@ -129,13 +103,6 @@ modules:
           - wine64 reg add 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /d '10.0' /f
           - wine64 reg add 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Windows' /v CSDVersion /t REG_DWORD /d 00000000 /f
           - 
-          - echo "Create Battle.net config"
-          - mkdir -p "${WINEPREFIX}/dosdevices/c:/users/${USER}/Application Data/Battle.net"
-          - 'echo "{ \"Client\": { \"HardwareAcceleration\": false, \"Sound\": { \"Enabled\": false } } }" > "${WINEPREFIX}/dosdevices/c:/users/${USER}/Application Data/Battle.net/Battle.net.config"'
-          - 
-          - echo "Installing application..."
-          - wine64 "${XDG_CACHE_HOME}/wow-installer.exe"
-          - 
           - echo "Installer finished"
       - type: script
         dest-filename: wow
@@ -150,10 +117,14 @@ modules:
           - '    fi'
           - fi
           - 
-          - wine64 "C:/Program Files (x86)/Battle.net/Battle.net Launcher.exe"
+          - echo "Verify \"Battle.net Helper.exe\" doesn't launch..."
+          - if [ -f "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Battle.net/Battle.net*/Battle.net Helper.exe" ] ; then
+          - '    mv "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Battle.net/Battle.net*/Battle.net Helper.exe" "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Battle.net/Battle.net*/Battle.net Helper.exe.bak"'
+          - fi
+          - 
+          - wine64 "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Battle.net/Battle.net Launcher.exe" "battlenet://WoW"
       - type: file
         path: com.blizzard.WoW.appdata.xml
       - type: file
         path: com.blizzard.WoW.desktop
-
 
